paths:
  /api/products:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: All products
        "500":
          description: Server error
        "400":
          desscription: Some data is missing
    post:
      summary: Create product
      tags:
        - Products
      responses:
        "200":
          description: Product created
        "500":
          description: Error al crear el producto
        "400":
          desscription: Some data is missing
    delete:
      summary: Delete product
      tags:
        - Products
      responses:
        "200":
          description: Product deleted
        "500":
          description: Error al crear el producto
        "400":
          desscription: Some data is missing

  /api/products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameteres:
        - name: id
          in: path
          description: Product identifier
      responses: 
        "200":
          description: One product found
          content:
            application/json:
              schemas:
                schemas:
                  $ref: "#/components/schemas/Product"
                example:
                  id: 456468fsf5
                  title: A
                  description: asdad
                  price: 12
                  thumbnail: dada
                  code: dasd4
                  stock: 34
                  category: asd
        "500":
          description: Server error
        "400":
          desscription: Some data is missing

    put:
      summary: Update product
      tags:
        - Products
      responses:
        "200":
          description: Product updated
        "500":
          description: Error updating
        "400":
          desscription: Some data is missing

components: 
  schemas:
    Product:
      type: object
      properties: 
        id:
          type: string
        title: 
          type: string
        description:
          type: string
        price:
          type: number
        thumbnail:
          type: string
        code:
          type: string
        stock:
          type: number
        category:
          type: string

      example:
        id: 456468fsf5
        title: A
        description: asdad
        price: 12
        thumbnail: dada
        code: dasd4
        stock: 34
        category: asd



